server:
  port: 0

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  main:
    web-application-type: none # don't start webserver
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false

  liquibase:
    enabled: true
    user: ${LIQUIBASE_COMMAND_USERNAME:${spring.datasource.username}}
    password: ${LIQUIBASE_COMMAND_PASSWORD:${spring.datasource.password}}
    change-log: classpath:db/changelog/db.changelog-master.xml

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/instance
    username: ${LIQUIBASE_COMMAND_USERNAME:}
    password: ${LIQUIBASE_COMMAND_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    # database-platform: org.hibernate.dialect.PostgreSQLDialect # hibernate 6 auto detects
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        jdbc:
          "[time_zone]": UTC
        "[format_sql]": true
        "[highligh_sql]": true
        "[use_sql_comments]": true
  kafka:
    bootstrap-servers: ${BROKER_HOST:localhost}:9092

eureka:
  client:
    enabled: false

management:
  server:
    port: 0

logging:
  level:
    liquibase: DEBUG
