spring:
  application:
    name: instance-service

info:
  app:
    name: ${spring.application.name}

app:
  skip-env-var: false
  config-keys:
    enable-signup: ${ENABLE_SIGNUP:1}
    enable-email-password: ${ENABLE_EMAIL_PASSWORD:1}
    disable-workspace-creation: ${DISABLE_WORKSPACE_CREATION:0}
    enable-smtp: ${ENABLE_SMTP:0}
    email-host: ${EMAIL_HOST:}
    email-host-user: ${EMAIL_HOST_USER:}
    email-host-passwrod: ${EMAIL_HOST_PASSWORD:}
    email-port: ${EMAIL_PORT:587}
    email-from: ${EMAIL_FROM:}
    email-use-tls: ${EMAIL_USE_TLS:1}
    email-use-ssl: ${EMAIL_USE_SSL:}
    enable-magic-link-login: ${ENABLE_MAGIC_LINK_LOGIN:0}
    google-client-id: ${GOOGLE_CLIENT_ID:}
    google-client-secret: ${GOOGLE_CLIENT_SECRET:}
    github-client-id: ${GITHUB_CLIENT_ID:}
    github-client-secret: ${GITHUB_CLIENT_SECRET:}
    gitlab-host: ${GITLAB_HOST:}
    gitlab-client-id: ${GITLAB_CLIENT_ID:}
    gitlab-client-secret: ${GITLAB_CLIENT_SECRET:}
  use-minio: true
  file-size-limit: 5242880
  debug: true
  hard-delete-after-days: 60
  web-url: http://${WEB_URL:localhost}
  secret-key: ${SECRET_KEY:}
  is-test: false
  base-urls:
    admin: "${ADMIN_BASE_URL:http://localhost:3001/god-mode/}"
    app: "${APP_BASE_URL:http://localhost:3000/}"

---
spring:
  config:
    activate:
      on-profile:
        - "!setup"
    import:
      - optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:8888/
