server:
  port: 8020
spring:
  application:
    name: email-service
  rabbitmq:
    addresses: amqp://sebastian:Twice_Mina1@${RABBITMQ_HOST:localhost}
  mail:
    host: smtp.gmail.com
    username: salsebastian13@gmail.com
    password: dwgx trqd nebn ecsf
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mail:
  debug: true

rabbitmq:
  exchanges:
    internal: direct.exchange
  queues:
    mail: q.mail
  routing-keys:
    internal-mail: user.mail-token