server:
  port: 8020
spring:
  application:
    name: email-service
  cloud:
    vault:
      scheme: http
      host: localhost
      port: 8200
      uri: http://localhost:8200
      authentication: TOKEN
      token: ${VAULT_TOKEN:ac57f855f2f444a3b28309d7342cd9249a731f95f3c38a618c5133bebf51e754}
      fail-fast: true
      config.lifecycle.enabled: true
      rabbitmq:
        enabled: true
        role: my-role
        backend: rabbitmq
        username-property: spring.rabbitmq.username
        password-property: spring.rabbitmq.password
  mail:
    host: smtp.gmail.com
    username: salsebastian13@gmail.com
    password: vngb ieei dyhj kuhw
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
mail:
  debug: true

rabbitmq:
  exchanges:
    internal-direct: email.exchange
    internal-fanout: user.events
  routing-keys:
    internal-mail: high_priority.mail
  queues:
    internal-fanout-queue: q.usersvc
    internal-mail: q.mail