server:
  port: 8022

spring:
  application:
    name: file-service
amazon:
  s3:
    bucket:
      task:
        name: taskattachment
      user:
        name: spidergwen
  aws:
    access-key: ${AWS_ACCESS_KEY:}
    secret-key: ${AWS_SECRET_KEY:}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: file-service
