server:
  port: 8002
spring:
  application:
    name: password-service
  cloud:
    vault:
      scheme: http
      host: localhost
      port: 8200
      uri: http://localhost:8200
      authentication: TOKEN
      token: ${VAULT_TOKEN:hvs.4N6YpNW0pl4ONeKbK99rHq0V}
#      ssl:
#        trust-store: file:${KEYSTORE:/Users/sebastian/IdeaProjects/personaVault/work/keystore.jks}
#        trust-store-password: changeit
      fail-fast: true
      config.lifecycle.enabled: true
      database:
        enabled: true
        role: password-service
        backend: database
        username-property: spring.datasource.username
        password-property: spring.datasource.password
      rabbitmq:
        enabled: true
        role: my-role
        backend: rabbitmq
        username-property: spring.rabbitmq.username
        password-property: spring.rabbitmq.password
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        temp:
          "[use_jdbc_metadata_defaults]": false
  liquibase:
    enabled: false
    user: sebastian
    password: Twice_Mina1
    change-log: classpath:db/changelog/db.changelog-master.xml
  rabbitmq:
    addresses: ${RABBITMQ_HOST:localhost}:5672
  kafka:
    bootstrap-servers: ${BROKER_HOST:localhost:9092}
    consumer:
      group-id: password

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${HOST_NAME:localhost}

rabbitmq:
  exchanges:
    internal-direct: email.exchange
    internal-fanout: user.events
  routing-keys:
    internal-mail: high_priority.mail
  queues:
    internal-fanout-queue: q.tasksvc
    internal-mail: q.mail