server:
  port: 8003
spring:
  application:
    name: task-service
  cloud:
    vault:
      scheme: https
      host: vault.twiceb.internal
      port: 8200
      uri: https://vault.twiceb.internal:8200
      authentication: TOKEN
      token: ${VAULT_TOKEN:hvs.Dja4eR4ujYtNUWiVrNXjFeqJ}
      ssl:
        trust-store: file:${KEYSTORE:/Users/sebastian/IdeaProjects/personaVault/work/keystore.jks}
        trust-store-password: changeit
      fail-fast: true
      config.lifecycle.enabled: true
      database:
        enabled: true
        role: task-service
        backend: database
        username-property: spring.datasource.username
        password-property: spring.datasource.password
      rabbitmq:
        enabled: true
        role: my-role
        backend: rabbitmq
        username-property: spring.rabbitmq.username
        password-property: spring.rabbitmq.password
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/task
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        temp:
          "[use_jdbc_metadata_defaults]": false
  liquibase:
    enabled: false
    user: sebastian
    password: Twice_Mina1
    change-log: classpath:db/changelog/db.changelog-master.xml
  rabbitmq:
    addresses: ${RABBITMQ_HOST:localhost}:5672
  kafka:
    bootstrap-servers: ${BROKER_HOST:localhost:9092}
    consumer:
      group-id: task

eureka:
  client:
    service-url:
      default-zone: http://${EUREKA_HOST:localhost}:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${HOST_NAME:localhost}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:9411
  tracing:
    sampling:
      probability: 1.0

rabbitmq:
  exchanges:
    internal-direct: email.exchange
    internal-fanout: user.events
  routing-keys:
    internal-mail: high_priority.mail
  queues:
    internal-fanout-queue: q.tasksvc
    internal-mail: q.mail