server:
  port: 8003
spring:
  application:
    name: task-service
  cloud:
    vault:
      scheme: http
      host: localhost
      port: 8200
      uri: http://localhost:8200
      authentication: TOKEN
      token: ${VAULT_TOKEN:b005f040d6002aa8a7e6339c99338ea8f4b6f8907f8f6084193ca3e9c49b1163}
      fail-fast: true
      config.lifecycle.enabled: true
      database:
        enabled: true
        role: task-service
        backend: database
        username-property: spring.datasource.username
        password-property: spring.datasource.password
      rabbitmq:
        enabled: true
        role: my-role
        backend: rabbitmq
        username-property: spring.rabbitmq.username
        password-property: spring.rabbitmq.password
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/task
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        temp:
          "[use_jdbc_metadata_defaults]": false
  liquibase:
    enabled: false
    user: sebastian
    password: Twice_Mina1
    change-log: classpath:db/changelog/db.changelog-master.xml
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
logging:
  level:
    root: INFO
    "[org.springframework.web]": DEBUG
    "[org.springframework.amqp]": DEBUG

rabbitmq:
  exchanges:
    internal-direct: email.exchange
    internal-fanout: user.events
  routing-keys:
    internal-mail: high_priority.mail
  queues:
    internal-fanout-queue: q.tasksvc
    internal-mail: q.mail