server:
  port: 8003
spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/task
    username: sebastian
    password: Twice_Mina1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        temp:
          "[use_jdbc_metadata_defaults]": false
  liquibase:
    enabled: false
    user: sebastian
    password: Twice_Mina1
    change-log: classpath:db/changelog/db.changelog-master.xml
  rabbitmq:
    addresses: amqp://task-service:${TASK_SERVICE_PW:fMK239wfugQeivEwwgNjzfR6ek}@${RABBITMQ_HOST:localhost}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
logging:
  level:
    root: INFO
    "[org.springframework.web]": DEBUG
    "[org.springframework.amqp]": DEBUG

rabbitmq:
  exchanges:
    internal-direct: email.exchange
    internal-fanout: user.events
  routing-keys:
    internal-mail: high_priority.mail
  queues:
    internal-fanout-queue: q.tasksvc
    internal-mail: q.mail