spring:
  cloud:
    vault:
      scheme: https
      host: vault.local
      port: 8400
      uri: https://vault.local:8400
      authentication: APPROLE
      app-role:
        role-id: ${VAULT_APPROLE_ROLE_ID}
        secret-id: ${VAULT_APPROLE_SECRET_ID}
        role: user-service
        app-role-path: approle
