server:
  port: 8001
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/user
    username: sebastian
    password: Twice_Mina1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        temp:
          "[use_jdbc_metadata_defaults]": false
  liquibase:
    enabled: false
    user: sebastian
    password: Twice_Mina1
    change-log: classpath:db/changelog/db.changelog-master.xml
  rabbitmq:
    addresses: amqp://user-service:${USER_SERVICE_PW:RHqKJXRqUoVoNmP8G58RA0uc}@${RABBITMQ_HOST:localhost}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
logging:
  level:
    "[org.springframework.cloud.amqp]": DEBUG

rabbitmq:
  exchanges:
    internal-direct: email.exchange
    internal-fanout: user.events
  routing-keys:
    internal-mail: high_priority.mail
  queues:
    internal-fanout-queue: q.usersvc
    internal-mail: q.mail