server:
  port: 8001
spring:
  application:
    name: user-service
  cloud:
    vault:
      uri: http://localhost:8200
      authentication: APPROLE
      app-role:
        role-id: ${VAULT_USER_SERVICE_ROLE_ID:}
        secret-id: ${VAULT_USER_SERVICE_SECRET_ID:}
#      ssl:
#        trust-store: file:${KEYSTORE:/Users/sebastian/IdeaProjects/personaVault/work/keystore.jks}
#        trust-store-password: changeit
      fail-fast: true
      config.lifecycle.enabled: true
      database:
        enabled: true
        role: user-service
        backend: database
        username-property: spring.datasource.username
        password-property: spring.datasource.password
        static-role: false
      rabbitmq:
        enabled: true
        role: my-role
        backend: rabbitmq
        username-property: spring.rabbitmq.username
        password-property: spring.rabbitmq.password
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    # database-platform: org.hibernate.dialect.PostgreSQLDialect # hibernate 6 auto-detects postgres
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        # temp:
        #   "[use_jdbc_metadata_defaults]": false // hibernate 5 era settings
  liquibase:
    enabled: true
    user: ${LIQUIBASE_USER:}
    password: ${LIQUIBASE_PW:}
    change-log: classpath:db/changelog/db.changelog-master.xml
  rabbitmq:
    addresses: ${RABBITMQ_HOST:localhost}:5672
  kafka:
    bootstrap-servers: ${BROKER_HOST:localhost:9092}
    consumer:
      group-id: user

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${HOST_NAME:localhost}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:9411
  tracing:
    sampling:
      probability: 1.0

rabbitmq:
  exchanges:
    internal-direct: email.exchange
    internal-fanout: user.events
  routing-keys:
    internal-mail: high_priority.mail
  queues:
    internal-fanout-queue: q.usersvc
    internal-mail: q.mail