server:
  port: 8006

spring:
  application:
    name: workspace-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/workspace
    driver-class-name: org.postgresql.Driver
    username: sebastian
    password: Twice_Mina1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    # database-platform: org.hibernate.dialect.PostgreSQLDialect # hibernate 6 auto detects
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        jdbc:
          "[time_zone]": UTC
        "[format_sql]": true
        "[highligh_sql]": true
        "[use_sql_comments]": true
        # temp:
        #   "[use_jdbc_metadata_defaults]": false # hibernate 5 era settigs
  liquibase:
    enabled: true
    # so it does not borrow the main datasource which vault populates later
    # removes any race with vaults datasoruce creds
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/workspace
    user: ${LIQUIBASE_COMMAND_USERNAME:}
    password: ${LIQUIBASE_COMMAND_PASSWORD:}
    change-log: classpath:db/changelog/db.changelog-master.xml
  # kafka:
  #   bootstrap-servers: ${BROKER_HOST:localhost:9092}
  #   consumer:
  #     group-id: user

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${HOST_NAME:localhost}

# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"
#   zipkin:
#     tracing:
#       endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans
#   tracing:
#     sampling:
#       probability: 1.0

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE # bound params (hibernate 6)